import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'

export default function Home() {
  const handleOnBannerButtonClick = () => {
    alert(5)
}
  return (
    <div className={styles.container}>
      <Head>
        <title>My Coffe Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    

      <main className={styles.main}>
      <Banner buttonText={'Find Local Shops'} handleOnClick={handleOnBannerButtonClick} />
      </main>
    </div>
  )
}
